# -*- coding: utf-8 -*-
"""Hatchet Archive Scrap v4 - kind of finished

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fs4c-EzPdmeqEARXCbZgyIElP-gJWczH
"""

import requests

from bs4 import BeautifulSoup

URL = 'https://www.gwhatchet.com/archives/'

r = requests.get(URL)

soup=BeautifulSoup(r.text)

body_class = soup.select_one('div.primary-container') #select div with just the volume headings and links

links = []
for link in body_class.find_all('a'):
    links.append(link.get('href'))

print(links)

"""8/24/22 - This script sucessfully pulls all of the links from the "primary container" div and adds them to a list, "links." Improvements could be made to also select the "volume" information from the h2 heading within the primary-container."""

import pandas

df = pandas.DataFrame(data={"Links": links})
df.to_csv("./hatchetlinks.csv", sep=',',index=False)



"""Using pandas to save list of links as csv"""